name: mirror github ibm

on:
  push:
    branches:
      - master
      - main
  schedule:
    # Run at 1AM (5AM UTC)
    - cron: "0 5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to use the GitHub API to trigger a webhook event 
  repository_dispatch:

jobs:
  mirror:
    uses: ibm-skills-network/.github/.github/workflows/mirror-github-ibm.yml@main
    with:
      repo_name: edx-manager-access-api
    secrets:
      ssh_private_key:
          ${{ secrets.MIRROR_GITHUB_IBM_SSH_PRIVATE_KEY }}
